service:
  name: kolabs

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  versionFunctions: false
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  timeout: 30
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - "arn:aws:dynamodb:us-east-2:*:*"
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"
    - Effect: Allow
      Action:
        - SQS:*
      Resource:
        - "arn:aws:sqs:us-east-2:*:*"
    - Effect: Allow
      Action:
        - SNS:*
      Resource:
        - "arn:aws:sns:us-east-2:*:*"
    - Effect: Allow
      Action:
        - s3:putObject
        - s3:deleteObject
        - s3:getObject
        - s3:listBucket
      Resource: "arn:aws:s3:::*/*"

functions:
  signUp:
    handler: handler.signUpHandler
    events:
      - http:
          method: post
          path: users/signUp
          cors: true
  logIn:
    handler: handler.logInHandler
    events:
      - http:
          method: post
          path: users/logIn
          cors: true
  authorizerFunc:
    handler: handler.authorizerFuncHandler

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    KolabsUsersTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "email"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "email"
            KeyType: "HASH"
        TableName: KolabsUsers
        BillingMode: PAY_PER_REQUEST
    KolabsCompaniesTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        TableName: KolabsCompanies
        BillingMode: PAY_PER_REQUEST
    KolabsCompaniesUsers:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "companyId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        TableName: KolabsCompaniesUsers
        BillingMode: PAY_PER_REQUEST
